REPLACE INTO `#__js_ticket_config` (`configname`, `configvalue`, `configfor`) VALUES ('versioncode','2.3.3','default');
REPLACE INTO `#__js_ticket_config` (`configname`, `configvalue`, `configfor`) VALUES ('productversion','233','default');
INSERT INTO `#__js_ticket_config`  (`configname`, `configvalue`, `configfor`, `addon`) VALUES
		('apikeylinkedin' ,'' , 'linkedin', 'sociallogin'),
        ('loginwithfacebook' ,'0' , 'login', 'sociallogin'),
        ('loginwithlinkedin' ,'0' , 'login', 'sociallogin'),
        ('apikeyfacebook' ,'' , 'facebook', 'sociallogin'),
        ('clientsecretfacebook' ,'' , 'facebook', 'sociallogin'),
        ('clientsecretlinkedin' ,'' , 'linkedin', 'sociallogin');
					
CREATE TABLE IF NOT EXISTS `#__js_ticket_users` (
  `id` bigint(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `wpuid` bigint(20),
  `name` varchar(250),
  `display_name` varchar(250),
  `user_nicename` varchar(250),
  `user_email` varchar(250) NOT NULL,
  `status` int(11) NOT NULL,
  `issocial` int(11),
  `socialid` varchar(250) NOT NULL,
  `autogenerated` int(2),
  `created` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `#__js_ticket_users` (`id`, `wpuid`, `name`, `display_name`,`user_nicename`,`user_email`, `issocial`, `socialid`, `status`, `autogenerated`,`created`)
SELECT `ID`,`ID`,user_nicename,display_name,user_nicename,user_email,0,'',1,0,NOW() FROM `#__users`;
